select * from emp;
select distinct job from emp;
select * from emp where hiredate<'01-JAN-81';
select * from emp where deptno=10 or deptno=20;
select * from emp where deptno=20 and job='CLERK';
select * from emp where ename='SMITH';
select dept.LOC from emp,dept where emp.deptno=dept.deptno and emp.ename='SMITH';
select ename from emp where (sal +(sal*0.2))>3000;
[x]x[][x]x[]x[select (select s2.grade from emp e2,salgrade s2 where e2.sal between s2.losal and s2.hisal and e2.empno=e1.empno),e1.ename from emp e1 where deptno in (10,30) and hiredate<'31-DEC-82' and (select s2.grade from emp e2,salgrade s2 where e2.sal between s2.losal and s2.hisal and e2.empno=e1.empno)<>4;
select * from emp where substr(hiredate,1,2)<15;
select * from emp where job='MANAGER';
select ename,'$' || (sal+(sal*0.15)) from emp;
select ename||' '||job as "EMP_AND_JOB" from emp;
select ename||' ('||job||')' as "EMPLOYEE" from emp;
select distinct dept.dname from dept,emp where dept.deptno=emp.deptno;
select * from emp where ename='BLAKE';
select ename from emp where job='CLERK';
select empno, sal, comm from emp;
[x]select distinct dept.dname from dept,emp where dept.deptno=emp.deptno;
select * from emp where hiredate='01-may-81';
select * from emp where job='MANAGER';
select * from emp where job='MANAGER' or job='CLERK';
select * from emp where hiredate='01-may-81' or hiredate='17-nov-81' or hiredate='30-dec-81';
select * from emp where substr(hiredate,8,2)=81;
select * from emp where sal>=2300 and sal<=4000;
[x][x]select * from emp where mgr=7369 or mgr=7890 or mgr=7654 or mgr=7900;
select * from emp where hiredate>='01-jul-82' and hiredate<='31-dec-82';
select ename,sal from emp where ename='MILLER' or ename='SMITH';
select ename,sal from emp where sal>1000;
select ename,sal from emp where ename<>'JAMES';
select * from emp where comm>sal;
select ename from emp where (sal * 12) >= 22000 or (sal * 12) <= 45000;
select ename,sal from emp where MGR IS NULL;
select ename from emp where ename like 'M%';
select ename from emp where ename like '%H';
select ename from emp where substr(hiredate,8,2)=81;
select ename from emp where sal like '%00';
select ename from emp where substr(hiredate,8,1)=8;
select ename from emp where job='CLERK' and (sysdate-hiredate)>8;
select * from emp where job='MANAGER' and (deptno = 10 or deptno=20);
select * from emp where ename like 'S%';
select ename from emp where ename like '%A%';
select ename from emp where ename like '___L%';
select ename from emp where ename like 'A%' or ename like 'M%';
select ename,job,sal,deptno from emp where job<>'SALESMAN' and deptno<>30;
select distinct dept.dname from dept,emp where dept.deptno=emp.deptno;
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
select ename as "Employee",sal as "Monthly Salary" from emp where sal > 1500 and (deptno=10 or deptno=30);
select ename,sal from emp where sal>=1500 and sal <=2850;
select ename,job,sal from emp where MGR IS NULL;
select ename,job,sal from emp where (job='MANAGER' or job='ANALYST') and (sal<>1000 and sal<>3000 and sal<>5000);
select ename,sal,comm from emp where comm>(sal+(sal*0.1));
select ename from emp where ename like '%L%L%' and (deptno=30 or mgr=7782);
select sal*12 from emp where ename='SMITH';
select sal/30 from emp where ename='JONES';
select SUM(sal) from emp;
select AVG(sal*12) from emp;
select * from emp where MOD(sal,2)=1;
select * from emp where LENGTH(sal)=3;
select * from emp where hiredate like '%DEC%';
select * from emp where ename like '%A%';
[x][x][x][x]select * from emp where instr(to_char(sal),deptno)<>0;
select ename,to_char(hiredate,'yy') from emp where (sal*0.1)=to_char(hiredate,'yy');
select lower(substr(ename,1,length(ename)/2))||upper(substr(ename,(length(ename)/2)+1)) from emp;
select ename from emp where add_months(hiredate,(20*12))>'31-DEC-89';
select * from emp order by sal;
select * from emp order by deptno;
select * from emp order by deptno asc,job desc;
select distinct job from emp order by job desc;
select empno,ename,sal,(sal/30),(sal*12) from emp order by (sal*12);
select empno,ename,to_char(sysdate,'YYYY')-to_char(hiredate,'YYYY') from emp where mgr=7698;
select * from emp where hiredate>'31-DEC-81' order by job;
select ename,(to_char(sysdate,'YYYY')-to_char(hiredate,'YYYY')) as "Experience",(sal/30) as "Daily Salary" from emp where sal/30>100;
select * from emp where job in ('CLERK','ANALYST');
select * from emp where hiredate in ('1-MAY-81','03-DEC-81','17-DEC-81','19-JAN-80') order by hiredate;
select * from emp where to_char(hiredate,'YY')=81;
select * from emp where to_char(hiredate,'MON-YY')='APR-81';
select * from emp where length(ename)=5;
select * from emp where length(ename)=5 and ename like 'S%';
select * from emp where length(ename)=4 and ename like '__r%';
select * from emp where ename like 'S%H';
select * from emp where to_char(hiredate,'MON')='JAN';
[x][x]select * from emp where to_char(hiredate,'MONTH') like '%a%';
select * from emp where length(sal)=4 and sal like '%0';
select * from emp where ename like '%LL%';
select * from emp where to_char(hiredate,'YY') between 80 and 89;
select * from emp where deptno<>20 and job not in ('PRESIDENT','MANAGER') order by sal;
select * from emp where (hiredate<'01-JAN-81' or hiredate>'31-DEC-81') and empno not like '78%';
select * from emp where to_char(hiredate,'MON')<>'MAR';
select * from emp where (deptno=10 or deptno=30) and to_char(hiredate,'YY')=81;
select max(sal) from emp;
select sum(sal) from emp where job='MANAGER';
select sum(sal*12),job from emp where hiredate<'01-JAN-82' group by job;
select e1.* from emp e1 where (select s.grade from emp e,salgrade s where e.sal between s.losal and s.hisal and e.empno=e1.empno)=3;
select avg(sal) from emp where job='CLERK';
select e1.*,to_char(hiredate,'MONTH DD, YYYY') from emp e1;
select e1.*,(case when e1.sal>1500 then 'Just Salary' when e1.sal=1500 then 'On Target' else 'Below 1500' end) from emp e1;
select to_char(sysdate,'Day') from dual;
select length(ename),ename from emp;
select count(empno) from emp where job='MANAGER';
select * from emp where sal<1000 order by sal;
select * from emp order by sal;
select deptno,empno,ename from emp order by job asc,ename desc;
select empno,ename,sal,deptno from emp where deptno=10 order by sal;
select * from emp where sal<3500;
select empno,ename,sal from emp where hiredate<'01-APR-81';
select * from emp where sal*12 < 25000 order by sal;
select empno,ename,sal*12 as "Annual Salary",sal/30 "Daily Salary" from emp order by (sal*12);
select empno,ename,hiredate,sysdate,(to_char(sysdate,'YYYY')-to_char(hiredate,'YYYY')) "Experience" from emp order by (to_char(sysdate,'YYYY')-to_char(hiredate,'YYYY'));
select * from emp where (to_char(sysdate,'YYYY')-to_char(hiredate,'YYYY'))>10;
select empno,ename,sal,(sal*0.3) as "TA",(sal*0.4) as "DA",(sal*0.5) as "HRA", sal+(sal*0.3)+(sal*0.4)+(sal*0.5) as "GROSS" from emp order by sal+(sal*0.3)+(sal*0.4)+(sal*0.5);
select * from emp where to_char(hiredate,'MON')='JAN';
select * from emp where to_char(hiredate,'MONTH') like '%A%';
select * from emp where to_char(hiredate,'MONTH') like '_A%';
select * from emp where to_char(hiredate,'MON')='JAN' and sal between 1500 and 4000;
select distinct job from emp where deptno in (20,30) order by job;
select e1.*,(to_char(sysdate,'YYYY')-to_char(e1.hiredate,'YYYY')) "Experience" from emp e1 where MGR is not NULL and to_char(hiredate,'YYYY')<1983 and empno like '7%' and empno not like '%9%';
select * from emp where job in ('MANAGER','ANALYST') and sal between 2000 and 5000 and comm is NULL;
select (to_char(sysdate,'YYYY')-to_char(hiredate,'YYYY')) "Experience" from emp where ename='MILLER';
select count(distinct deptno) from emp;
select e1.* from emp e1,dept d1 where d1.dname in ('SALES','RESEARCH') and d1.deptno=e1.deptno;
select d1.dname,avg(e1.sal) from emp e1,dept d1 where e1.deptno=d1.deptno group by d1.dname;
select min(sal) "Minimum",max(sal) "Maximum" from emp;
select d1.dname,min(e1.sal) "Minimum",max(e1.sal) "Maximum" from emp e1,dept d1 where e1.deptno=d1.deptno group by d1.dname;
select * from emp where sal<1000 and job='CLERK';
select count(*),job from emp group by job;
select m1.empno,count(e1.empno) from emp m1,emp e1 where e1.mgr=m1.empno group by m1.empno;
select s.grade,count(*) "No. of Employees",max(e.sal) from emp e, salgrade s where e.sal between s.losal and s.hisal group by s.grade;
[x][x][x][]x[x[x]select d.dname,s.grade,count(*) from dept d,salgrade s,emp e where d.deptno=e.deptno and e.sal between s.losal and s.hisal group by d.dname;
select count(*),deptno from emp group by deptno having count(*)>3;
select d.dname from emp e,dept d where e.deptno=d.deptno group by dname having count(*)>=3;

select * from emp where sal in (select min(sal) from emp group by job) and job in (select job from emp group by job) order by sal;
select * from emp where sal in (select max(sal) from emp group by job) and job in (select job from emp group by job) order by sal desc;
select * from emp e where e.hiredate >= (select max(e1.hiredate) from emp e1 where e1.deptno=e.deptno);
select e.ename,e.sal,e.deptno from emp e where e.sal > (select avg(e1.sal) from emp e1 where e.deptno=e1.deptno);
select d.deptno from dept d where (select count(*) from emp e1 where d.deptno=e1.deptno)=0;
[x]select count(*),avg(sal),job,deptno from emp group by deptno,job;

select * from emp where job='MANAGER';
(select e.* from emp e where (select s1.grade from salgrade s1 where e.sal between s1.losal and s1.hisal) in (2,3)) union (select e1.* from emp e1 where (select s.grade from salgrade s where e1.sal between s.losal and s.hisal) in (4,5) and e1.job in ('ANALYST','MANAGER'));

select * from emp where sal>(select sal from emp where ename='BLAKE');



select * from emp where deptno=20 and job in (select job from emp where deptno=10);
select * from emp where sal in (select sal from emp where ename in ('FORD','SMITH')) order by sal;
select * from emp where job=(select job from emp where ename='MILLER') or sal>(select sal from emp where ename='ALLEN');

select e.* from emp e where e.hiredate<(select hiredate from emp where ename='BLAKE') and (select d.loc from dept d where d.deptno=e.deptno) in ('CHICAGO','BOSTON');
alter table emp modify sal number(8,2);


create or replace view emp_view1 as select * from emp where deptno=10;
245. select * from (select * from emp order by sal) where rownum<=5;
